
---@class circle_data
---@field units_hit number
---@field best_unit game_object
---@field best_position vec3
---@field best_units game_objects_table

---@class circle
---@field center vec3
---@field radius number
---@field create fun(self: circle, center: vec3, radius: number): circle
---@field is_inside fun(self: circle, point: vec3, hitbox: number): boolean
---@field get_units_inside fun(self: circle, units_list: game_objects_table): game_objects_table
---@field get_allies_inside fun(self: circle, units_list_override: game_objects_table?): game_objects_table
---@field get_enemies_inside fun(self: circle, units_list_override: game_objects_table?): game_objects_table
---@field draw fun(self: circle): nil
---@field draw_with_counter fun(self: circle, units_hit_count: number?): nil
---@field get_optimal_hit_position fun(self: circle, search_center: vec3, search_radius: number, max_range: number, include_enemies: boolean, include_allies: boolean): circle_data

---@class rectangle
---@field corner1 vec3
---@field corner2 vec3
---@field corner3 vec3
---@field corner4 vec3
---@field width number
---@field length number
---@field origin vec3
---@field destination vec3
---@field create fun(self: rectangle, origin: vec3, destination: vec3, width: number, length: number?): rectangle
---@field create_direction fun(self: rectangle, position: vec3, direction: vec3, width: number, length: number): rectangle
---@field is_inside fun(self: rectangle, point: vec3, hitbox: number): boolean
---@field get_units_inside fun(self: rectangle, units_list: game_objects_table): game_objects_table
---@field get_allies_inside fun(self: rectangle, units_list_override: game_objects_table?): game_objects_table
---@field get_enemies_inside fun(self: rectangle, units_list_override: game_objects_table?): game_objects_table
---@field draw fun(self: rectangle): nil
---@field draw_with_counter fun(self: rectangle, count: number?): nil

---@class cone
---@field center vec3
---@field radius number
---@field angle_raw number
---@field angle number
---@field direction vec3
---@field path_around_cone vec3_table
---@field right_side_circ_points vec3_table
---@field left_side_circ_points vec3_table
---@field left_line_points vec3_table
---@field right_line_points vec3_table
---@field extra_left_point vec3_table
---@field extra_right_point vec3_table
---@field create fun(self: cone, center: vec3, destination: vec3, radius: number, angle: number): cone
---Function to create a cone given a position, radius, angle, and direction
---Note: Direction is obj:direction()
---@field create_direction fun(self: cone, center: vec3, direction: vec3, radius: number, angle: number): cone
---@field create_unit_frontal fun(self: cone, unit: game_object, radius: number, angle: number): cone
---@field get_path fun(self: cone, cone_info: table): nil
---@field is_inside fun(self: cone, point_position: vec3, hitbox: number): boolean
---@field get_units_inside fun(self: cone, units_list: game_objects_table): game_objects_table
---@field get_allies_inside fun(self: cone, units_list_override: game_objects_table?): game_objects_table
---@field get_enemies_inside fun(self: cone, units_list_override: game_objects_table?): game_objects_table
---@field draw fun(self: cone, color?:color, thickness?:number): nil
---@field draw_with_counter fun(self: cone, count: number?): nil
