
-- Example:
-- ---@type icons_helper
-- local icons = require("common/utility/icons_helper")
-- icons: -> IntelliSense
-- Warning: Access functions with ":", not "."
-- Note: Static members (cache/constants) are accessed with "."

---@class icons_helper
---@field public cache table<string, any>
---@field public ZAMIMG_BASE string
---@field public DEFAULT_SIZE string
---@field public DEFAULT_DISK_CACHE_FOLDER string
---@field public DEFAULT_HTTP_THROTTLE_SECONDS number
---@field public DEFAULT_PROBE_THROTTLE_SECONDS number
---@field public WOWHEAD_SPELL_BASE string
---@field public DEFAULT_SPELL_CACHE_FILE string
---@field public MAX_REDIRECTS number

---@class icons_helper_icon_entry
---@field public key string
---@field public name string
---@field public size string
---@field public file_stem string
---@field public url_jpg string
---@field public url_png string
---@field public cache_path_jpg string|nil
---@field public cache_path_png string|nil
---@field public tex_id integer|nil
---@field public w integer|nil
---@field public h integer|nil
---@field public requested boolean
---@field public error string|nil
---@field public dead boolean
---@field public dead_logged boolean
---@field public next_probe_time number
---@field public next_download_time number
---@field public prefer_ext string
---@field public tried_png boolean
---@field public tried_jpg boolean

---@class icons_helper_draw_opts
---@field public size string|nil                -- "large" | "medium" | "small"
---@field public persist_to_disk boolean|nil    -- default true
---@field public disk_cache_folder string|nil   -- default "cache\\wowhead_icons"

---@class icons_helper
---@field public draw_icon fun(self: icons_helper, icon_name_or_url: string, position: vec2|vec3, width: number, height: number, tint?: color, is_for_window?: boolean, opts?: icons_helper_draw_opts): boolean
---@field public draw_spell_icon fun(self: icons_helper, spell_id: number, position: vec2|vec3, width: number, height: number, tint?: color, is_for_window?: boolean, opts?: icons_helper_draw_opts): boolean
---@field public get_spell_icon_name fun(self: icons_helper, spell_id: number): string|nil
---@field public clear_cache fun(self: icons_helper): nil

--------------------------------------------------------------------------------
-- EXAMPLES (copy into your plugin)
--------------------------------------------------------------------------------
--
-- Example 1, draw one icon by name (wowhead slug style)
--
-- local vec2 = require("common/geometry/vector_2")
-- local icons_helper = require("common/utility/icons_helper")
-- local color = require("common/color")
--
-- local function on_render()
--     icons_helper:draw_icon(
--         "classicon-warlock",
--         vec2.new(30, 30),
--         64, 64,
--         color.white(255),
--         false,
--         {
--             size = "large",
--             persist_to_disk = true,
--         }
--     )
-- end
-- core.register_on_render_callback(on_render)
--
--
-- Example 2, draw an icon at a world position (vec3 -> w2s)
--
-- local vec3 = require("common/geometry/vector_3")
-- local icons_helper = require("common/utility/icons_helper")
--
-- local function on_render()
--     local world_pos = vec3.new(123.0, 456.0, 78.0)
--     icons_helper:draw_icon(
--         "classicon-warlock",
--         world_pos,
--         32, 32
--     )
-- end
-- core.register_on_render_callback(on_render)
--
--
-- Example 3, draw an icon resolved dynamically from a spell ID
--
-- local vec2 = require("common/geometry/vector_2")
-- local icons_helper = require("common/utility/icons_helper")
-- local color = require("common/color")
--
-- local function on_render()
--     -- Spell 100 = Charge -> scrapes Wowhead once -> "ability_warrior_charge"
--     icons_helper:draw_spell_icon(
--         100,
--         vec2.new(30, 30),
--         64, 64,
--         color.white(255),
--         false,
--         {
--             size = "large",
--             persist_to_disk = true,
--         }
--     )
-- end
-- core.register_on_render_callback(on_render)
--
--
-- Example 4, resolve a spell icon name without drawing
--
-- local icons_helper = require("common/utility/icons_helper")
--
-- local function on_update()
--     local name = icons_helper:get_spell_icon_name(100)
--     if name then
--         -- name == "ability_warrior_charge"
--         core.log("Resolved: " .. name)
--     end
-- end
-- core.register_on_update_callback(on_update)

---@type icons_helper
local tbl
return tbl
