
---@class tree_node
---@field is_open fun():boolean
---@field render fun(self:tree_node, header:string, callback:function):nil
---@field get_widget_bounds fun(self:tree_node):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field set_open_state fun(self:tree_node, state:boolean):nil
---@field set fun(self:checkbox, nil):nil -- Dummy function. Do not use. This is for you to be able to loop menu elements and set them all to default without any LUA errors.
---@field get fun(self:checkbox):nil

---@class checkbox
---@field get_state fun():boolean
---@field get_type fun(self:checkbox)
---@field set fun(self: checkbox, new_state:boolean):nil
---@field render fun(self:checkbox, label:string, tooltip:string|nil):nil
---@field get_widget_bounds fun(self:checkbox):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field set fun(self:checkbox, val:boolean):nil
---@field get_default fun(self:checkbox):boolean

---@class key_checkbox
---@field get_main_checkbox_state fun(self:key_checkbox):boolean
---@field get_key_code fun(self:key_checkbox):integer
---@field get_keybind_state fun(self:key_checkbox):boolean
---@field set_toggle_state fun(self:key_checkbox, state:boolean):nil
---@field set_key fun(self:key_checkbox, key:integer):nil
---@field set_mode fun(self:key_checkbox, mode:integer):nil
---@field should_show_on_control_panel fun(self:key_checkbox):boolean
---@field get_mode fun(self:key_checkbox):integer -- 0 is hold, 1 is toggle, 2 is always
---@field get_type fun(self:key_checkbox)
---@field render fun(self:key_checkbox, label:string, tooltip:string|nil):nil

---@class slider_int
---@field get fun():number
---@field get_type fun(self:slider_int)
---@field set fun(self:slider_int, new_value:integer):nil
---@field render fun(self:slider_int, label:string, tooltip:string|nil):nil
---@field get_widget_bounds fun(self:slider_int):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field set fun(self:slider_int, val:integer):nil
---@field get fun(self:slider_int):integer

---@class slider_float
---@field get fun():number
---@field get_type fun(self:slider_float)
---@field set fun(self:slider_float, new_value:number):nil
---@field render fun(self:slider_float, label:string, tooltip:string|nil):nil
---@field get_widget_bounds fun(self:slider_float):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field set fun(self:slider_float, val:number):nil
---@field get fun(self:slider_float):number

---@class combobox
---@field get fun():number
---@field get_type fun(self:combobox)
---@field get_label fun(self:keybind):string -- The menu element needs to be rendered for this to return a string different than ""
---@field get_widget_bounds fun(self:combobox):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field set fun(self:combobox, new_value:number):nil
---@field is_showing_on_control_panel fun(self:combobox):boolean
---@field set_is_showing_on_control_panel fun(self:combobox):nil
---@field render fun(self:combobox, label:string, options:table, tooltip:string|nil):nil
---@field set fun(self:combobox, val:integer):nil
---@field get fun(self:combobox):integer

---@class combobox_reorderable
---@field get fun():number
---@field get_type fun(self:combobox_reorderable)
---@field render fun(self:combobox_reorderable, label:string, options:table, tooltip:string|nil):nil
---@field set fun(self:combobox_reorderable, val:integer):nil
---@field get fun(self:combobox_reorderable):integer

---@class keybind
---@field get_type fun(self:keybind)
---@field get_label fun(self:keybind):string -- The menu element needs to be rendered for this to return a string different than ""
---@field get_state fun(self:keybind):boolean
---@field get_key_code fun(self:keybind):integer
---@field get_widget_bounds fun(self:keybind):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field get_toggle_state fun(self:keybind):boolean
---@field set_key fun(self:keybind, new_key:number):nil
---@field set_is_showing_on_control_panel fun(self:keybind):nil
---@field is_showing_on_control_panel fun(self:keybind):boolean
---@field set_toggle_state fun(self:keybind, new_state:boolean):nil
---@field render fun(self:keybind, label:string, tooltip:string|nil, add_separator:boolean|nil):nil
---@field set fun(self:keybind, val:integer):nil
---@field get fun(self:keybind):integer

---@class button
---@field get_type fun(self:button)
---@field is_clicked fun(self:button):boolean
---@field get_widget_bounds fun(self:button):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field render fun(self:button, label:string, tooltip:string|nil):nil
---@field set fun(self:checkbox, nil):nil -- Dummy function. Do not use. This is for you to be able to loop menu elements and set them all to default without any LUA errors.
---@field get fun(self:checkbox):nil

---@class text_input
---@field get_type fun(self:text_input)
---@field get_text fun(self:text_input):string
---@field get_widget_bounds fun(self:text_input):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field get_text_as_number fun(self:text_input):number
---@field render fun(self:text_input, label:string, tooltip:string|nil):nil
---@field render_custom fun(self:text_input, label:string, tooltip:string, frame_bg:color, border_color:color, text_selected_bg_col:color, text_color:color, width_offset:number, height_offset:number|nil):nil
---@field set fun(self:text_input, val:string):nil
---@field get fun(self:text_input):integer

---@class color_picker
---@field get fun():color
---@field get_type fun(self:color_picker)
---@field get_widget_bounds fun(self:color_picker):table -- Returns a table with 2 elements, min and max. get_widget_bounds().min is the left border of the widget, and .max is the right border.
---@field render fun(self:color_picker, label:string, tooltip:string|nil):nil
---@field set fun(self:color_picker, val:color):nil
---@field get fun(self:color_picker):color
---@field get_default fun(self:color_picker):color

---@class header
---@field get_type fun(self:header)
---@field render fun(self:header, label:string, color:color):nil
---@field set fun(self:checkbox, nil):nil -- Dummy function. Do not use. This is for you to be able to loop menu elements and set them all to default without any LUA errors.
---@field get fun(self:checkbox):nil

---@class window
---@field set_window_cross_round fun(self:window):nil
---@field set_initial_size fun(self:window, size:vec2):nil
---@field set_initial_position fun(self:window, pos:vec2):nil
---@field set_visibility fun(self:window, visibility:boolean):nil
---@field set_next_widget_width fun(self:window, width:number):nil
---@field set_next_window_padding fun(self:window, padding:vec2):nil
---@field set_next_window_min_size fun(self:window, min_size:vec2):nil
---@field set_next_window_items_spacing fun(self:window, spacing:vec2):nil
---@field set_next_window_items_inner_spacing fun(self:window, inner_spacing:vec2):nil

---@class window
---@field get_size fun(self:window):vec2
---@field get_position fun(self:window):vec2
---@field get_mouse_pos fun(self:window):vec2
---@field get_text_size fun(self:window, text:string):vec2
---@field get_wrapped_text_size fun(self:window, text:string, width:number):vec2 -- Returns the size of the text when wrapped to the given width
---@field force_window_size fun(self:window, size:vec2):nil
---@field get_text_centered_x_pos fun(self:window, text:string):number
---@field set_current_context_dynamic_drawing_offset fun(self:window, offset:vec2):nil
---@field get_current_context_dynamic_drawing_offset fun(self:window):vec2
---@field add_artificial_item_bounds fun(self:window, bounds_start:vec2, bounds_end:vec2, id:string):nil
---@field get_available_region fun(self:window):vec2 -- Returns the available region size for content
---@field get_min_size fun(self:window):vec2 -- Returns the minimum size of the window
---@field get_scroll fun(self:window):vec2 -- Returns the current scroll position (x, y)
---@field get_max_scroll_y fun(self:window):number -- Returns the maximum scroll Y value
---@field set_scroll_y fun(self:window, scroll:number):nil -- Sets the scroll Y position
---@field center_text fun(self:window, text:string):nil -- Centers the text horizontally in the window

---@class window
---@field is_being_shown fun(self:window):boolean
---@field render_tooltip_default fun(self:window, text:string):nil
---@field is_animation_finished fun(self:window, id:integer):boolean
---@field is_mouse_button_pressed fun(self:window, button:integer):boolean
---@field is_mouse_button_clicked fun(self:window, button:integer):boolean
---@field is_rect_clicked fun(self:window, rect_min:vec2, rect_max:vec2):boolean
---@field push_item fun(self:window, label:string):nil
---@field pop_item fun(self:window):nil
---@field is_window_clicked fun(self:window):boolean
---@field is_window_hovered fun(self:window):boolean
---@field is_window_double_clicked fun(self:window):boolean
---@field is_window_focused fun(self:window):boolean -- Returns true if the window is currently focused
---@field is_any_item_active fun(self:window):boolean -- Returns true if any item is currently active
---@field stop_forcing_size fun(self:window):nil
---@field is_rect_pressed fun(self:window, rect_min:vec2, rect_max:vec2):boolean
---@field is_mouse_hovering_rect fun(self:window, rect_min:vec2, rect_max:vec2):boolean
---@field set_focus fun(self:window):nil -- Forces the window to be focused (when focused, a window will be rendered on top of all other windows and will begin accepting inputs)
---@field is_mouse_hovering_rect_block_movement fun(self:window, rect_min:vec2, rect_max:vec2):boolean -- Automatically blocks the window movement when true
---@field is_rect_double_clicked fun(self:window, rect_min:vec2, rect_max:vec2):boolean
---@field render_tooltip_text_only fun(self:window, text:string, text_color:color):nil
---@field render_tooltip_custom fun(self:window, text:string, text_color:color, background_color:color, border_color:color, faded_rects_color:color, x_text_offset:number, y_text_offset:number, faded_rects_y_thickness:number, faded_rects_x_thickness:number):nil

---@class window
---@field render_text fun(self:window, font_id:integer, pos_offset:vec2, col:color, text:string):nil
---@field render_text_custom_size fun(self:window, font_id:integer, pos_offset:vec2, col:color, font_size:number, text:string):nil -- Renders text with a custom font size
---@field render_text_wrapped fun(self:window, text:string, color:color, max_wrap_width:number):nil -- Renders text that wraps at the given width
--note: you can also pass special rect rounding flags after the thickness parameter (up to 4 flags, integers). Check enums to see what these flags mean.
---@field render_rect fun(self:window, pos_min_offset:vec2, pos_max_offset:vec2, col:color, rounding:number, thickness:number):nil
--note: you can also pass special rect rounding flags after the thickness parameter (up to 4 flags, integers). Check enums to see what these flags mean.
---@field render_rect_filled fun(self:window, pos_min_offset:vec2, pos_max_offset:vec2, col:color, rounding:number, flags:table|nil):nil
--note: you can also pass special rect rounding flags after the thickness parameter (up to 4 flags, integers). Check enums to see what these flags mean.
---@field render_rect_filled_multicolor fun(self:window, pos_min_offset:vec2, pos_max_offset:vec2, col_upr_left:color, col_upr_right:color, col_bot_right:color, col_bot_left:color, rounding:number, flags:table|nil):nil
---@field render_circle fun(self:window, center:vec2, radius:number, color:color, thickness:number):nil
---@field render_circle_filled fun(self:window, center:vec2, radius:number, color:color):nil
---@field render_bezier_quadratic fun(self:window, p1:vec2, p2:vec2, p3:vec2, color:color, thickness:number, num_segments:integer):nil
---@field render_bezier_cubic fun(self:window, p1:vec2, p2:vec2, p3:vec2, p4:vec2, color:color, thickness:number, num_segments:integer):nil
---@field render_triangle fun(self:window, p1:vec2, p2:vec2, p3:vec2, col:color, thickness:number):nil
---@field render_triangle_filled fun(self:window, p1:vec2, p2:vec2, p3:vec2, col:color):nil
---@field render_triangle_filled_multi_color fun(self:window, p1:vec2, p2:vec2, p3:vec2, col_1:color, col_2:color, col_3:color):nil
---@field render_line fun(self:window, p1:vec2, p2:vec2, col:color, thickness:number):nil
--- sets the background of the window (call before begin) to a multi-colored rectangle with the given colors. If this function is called, the color passed to the begin function is ignored.
---@field set_background_multicolored fun(self:window, top_left_color:color, top_right_color:color, bot_right_color:color, bot_left_color:color)nil
---forces the next window position. Call before begin.
---@field force_next_begin_window_pos fun(self:window, position:vec2):nil
---stops forcing the next window position 
---@field stop_forcing_position fun(self:window):nil
---function to avoid console errors when calling set_next_window_padding or spacing
---@field set_end_called_state fun(self:window):nil
---@field copy_to_clipboard fun(self:window, text:string):nil
---@field get_clipboard_text fun(self:window):string

---@class window
---@field push_font fun(self:window, font_id:integer):nil
---@field pop_font fun(self:window):nil -- Pops the previously pushed font
---@field add_menu_element_pos_offset fun(self:window, pos_offset:vec2):nil
---@field begin_group fun(self:window, begin_func:function):nil
---@field begin_window_sub_context fun(self:window, offset:vec2, add_flags:boolean, begin_func:function):nil
---@field set_next_window_close_cross_pos_offset fun(self:window, offset:vec2):nil
---@field render_text_clipped fun(self:window, rect_start:vec2, rect_end:vec2, text:string):nil
---@field block_input_capture fun(self:window):nil
---@field begin_popup fun(self:window, bg_color:color, border_color:color, size:vec2, pos:vec2, is_close_on_release:boolean, is_triggering_from_button:boolean, begin_func:function):boolean
---@field push_clip_rect fun(self:window, min:vec2, max:vec2, intersect:boolean):nil -- Pushes a clipping rectangle onto the stack
---@field pop_clip_rect fun(self:window):nil -- Pops the previously pushed clipping rectangle
---@field set_id fun(self:window, id:string):nil -- Sets the window ID
---@field get_type fun(self:window):integer -- Returns the window type
---@field set_render_layer fun(self:window, layer:integer):nil -- Sets the render layer for the window
---@field get_close_cross_bounds fun(self:window):table -- Returns a table with min and max vec2 representing the close cross bounds relative to window position
--note: you can also pass special_window_flag_1:integer, special_window_flag_2:integer, special_window_flag_3:integer after the cross_style parameter. Check enums to see what these parameters represent

---@class window
local window = {}

--- Begins rendering the window with various options.
--- @param self window The window object.
--- @param resizing_flag integer The flag for resizing options.
--- @param is_adding_close_cross boolean Whether to add a close cross to the window.
--- @param bg_color color The background color of the window.
--- @param border_color color The border color of the window.
--- @param cross_style integer The style of the close cross.
--- @param begin_func function The function to execute when beginning the window.
--- @return boolean Indicates if the window is open.
--- @overload fun(self: window, resizing_flag: integer, is_adding_close_cross: boolean, bg_color: color, border_color: color, cross_style: integer, special_window_flag_1: integer, begin_func: function): boolean
--- @overload fun(self: window, resizing_flag: integer, is_adding_close_cross: boolean, bg_color: color, border_color: color, cross_style: integer, special_window_flag_1: integer, special_window_flag_2: integer, begin_func: function): boolean
--- @overload fun(self: window, resizing_flag: integer, is_adding_close_cross: boolean, bg_color: color, border_color: color, cross_style: integer, special_window_flag_1: integer, special_window_flag_2: integer, special_window_flag_3: integer, begin_func: function): boolean
function window:begin(resizing_flag, is_adding_close_cross, bg_color, border_color, cross_style, begin_func, ...)
    -- Function implementation
    return false
end

---@class window
---@field draw_next_dynamic_widget_on_new_line fun(self:window):nil
---@field draw_next_dynamic_widget_on_same_line fun(self:window, offset_from_start:number|nil, spacing:number|nil):nil
---@field add_text_on_dynamic_pos fun(self:window, col:color, text:string):nil
---@field add_separator fun(self:window, right_sep_offset:number, left_sep_offset:number, y_offset:number, width_offset:number, custom_color:color):nil
---@field animate_widget fun(self:window, animation_id:integer, start_pos:vec2, end_pos:vec2, starting_alpha:integer, max_alpha:integer, alpha_speed:number, movement_speed:number, only_once:boolean):table
---@field make_loading_circle_animation fun(self:window, id:integer, center:vec2, radius:number, color:color, thickness:number, animation_type:integer)
